# Site settings
title:          Tale
description:    "Minimal Jekyll theme for storytellers"
url:            "https://chesterhow.github.io"

# Author
author:
  name:         Chester How
  url:          https://chester.how
  email:        chesterhow@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

remote_theme: chesterhow/tale

permalink:    /:year-:month-:day/:title
paginate:     5

plugins:
  - jekyll-paginate
  - jekyll-remote-theme
